# Generated by Django 6.0.1 on 2026-02-25 11:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="temp", editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="temp", editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="temp", editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
    ]
