# Generated by Django 6.0.1 on 2026-02-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_brand_slug_category_slug_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
