# Generated by Django 6.0.1 on 2026-02-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_thumbnail_productimage"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_category_per_parent",
        ),
    ]
